apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: user-data
spec:
  externalTrafficPolicy: Local
  type: NodePort   # type of the service.(ClusterIP, LoadBalancer, NodePort)
  ports:
    - port: 8080
      targetPort: 8080 # The port exposed by the service
