apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: user-data
spec:
  selector:
    matchLabels:
      app: user-data
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: user-data
    spec:
      containers:
        - name: user-data
          image: user-data:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster